[package]
name = "pomky"
version = "1.0.0"
edition = "2021"

[dependencies]
gtk = "0.15.5"
gdk = { version = "0.15.4", features = ["v3_22"] }
sysinfo = "0.24.6"
serde = "1.0.139"
serde_derive = "1.0.139"
serde_json = "1.0.82"
once_cell = "1.13.0"
